spring:
    application:
        name: 'chat'
    jpa:
        hibernate:
            ddl-auto: 'create-drop'
    session:
        store-type: 'redis'
    data:
        redis:
            repositories:
                enabled: false
async:
    executor:
        core_pool_size: 5
        max_pool_size: 10
        queue_capacity: 10
