spring:
    application:
        name: 'chat'
    jpa:
        hibernate:
            ddl-auto: 'create-drop'
        open-in-view: false
    session:
        store-type: 'redis'
    data:
        redis:
            repositories:
                enabled: false
